**IMPORT LIBRARY**

In [ ]:
import pandas as pd
import numpy as np

!pip install chefboost
from chefboost import Chefboost as chef

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting chefboost
  Downloading chefboost-0.0.17-py3-none-any.whl (26 kB)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.8/dist-packages (from chefboost) (1.21.6)
Requirement already satisfied: psutil>=5.4.3 in /usr/local/lib/python3.8/dist-packages (from chefboost) (5.4.8)
Requirement already satisfied: pandas>=0.22.0 in /usr/local/lib/python3.8/dist-packages (from chefboost) (1.3.5)
Requirement already satisfied: tqdm>=4.30.0 in /usr/local/lib/python3.8/dist-packages (from chefboost) (4.64.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.22.0->chefboost) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.22.0->chefboost) (2022.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.7.3->pandas>=0.22.0->chefboost) (1.15.0)
Installing collected packages: chefboost
Successfully installed chefboost-0.0.17

**LOAD DATASET**

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/kuliah/Smester 5/big data & data mining/p10/PlayTennis.csv")

In [ ]:
df.head()

    Outlook Temperature Humidity    Wind Play Tennis
0     Sunny         Hot     High    Weak          No
1     Sunny         Hot     High  Strong          No
2  Overcast         Hot     High    Weak         Yes
3      Rain        Mild     High    Weak         Yes
4      Rain        Cool   Normal    Weak         Yes

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Outlook      14 non-null     object
 1   Temperature  14 non-null     object
 2   Humidity     14 non-null     object
 3   Wind         14 non-null     object
 4   Play Tennis  14 non-null     object
dtypes: object(5)
memory usage: 688.0+ bytes

In [ ]:
# see what class inside column
for (columnName, columnData) in df.iteritems():
  print('Column Name : ', columnName)
  print('Çolumn Unique : ', set(columnData.values), '\n')

Column Name :  Outlook
Çolumn Unique :  {'Sunny', 'Overcast', 'Rain'}

Column Name :  Temperature
Çolumn Unique :  {'Cool', 'Hot', 'Mild'}

Column Name :  Humidity
Çolumn Unique :  {'High', 'Normal'}

Column Name :  Wind
Çolumn Unique :  {'Strong', 'Weak'}

Column Name :  Play Tennis
Çolumn Unique :  {'Yes', 'No'}

**CRAETE CLASSIFIER MODEL**

In [ ]:
# set config to use c45 algorithm
config = {'algorithm':'C4.5'}

# training c4.5 model on the training set
c45_model = chef.fit(df, config, target_label = 'Play Tennis')

[INFO]:  1 CPU cores will be allocated in parallel running
C4.5  tree is going to be built...
-------------------------
finished in  0.4298737049102783  seconds
-------------------------
Evaluate  train set
-------------------------
Accuracy:  100.0 % on  14  instances
Labels:  ['No' 'Yes']
Confusion matrix:  [[5, 0], [0, 9]]
Precision:  100.0 %, Recall:  100.0 %, F1:  100.0 %

**SHOW RESULT**

In [ ]:
with open('/content/outputs/rules/rules.py', encoding='utf-8') as f:
  for line in f:
    print(line.strip())

def findDecision(obj): #obj[0]: Outlook, obj[1]: Temperature, obj[2]: Humidity, obj[3]: Wind
# {"feature": "Outlook", "instances": 14, "metric_value": 0.9403, "depth": 1}
if obj[0] == 'Sunny':
# {"feature": "Humidity", "instances": 5, "metric_value": 0.971, "depth": 2}
if obj[2] == 'High':
return 'No'
elif obj[2] == 'Normal':
return 'Yes'
else: return 'Yes'
elif obj[0] == 'Rain':
# {"feature": "Wind", "instances": 5, "metric_value": 0.971, "depth": 2}
if obj[3] == 'Weak':
return 'Yes'
elif obj[3] == 'Strong':
return 'No'
else: return 'No'
elif obj[0] == 'Overcast':
return 'Yes'
else: return 'Yes'

**PREDICTION**

In [ ]:
# predict berdasarkan row

print('Row : \n : ', df.loc[2])
print('\nPrediction : ', chef.predict(c45_model, df.loc[2]))

Row :
 :  Outlook        Overcast
Temperature         Hot
Humidity           High
Wind               Weak
Play Tennis         Yes
Name: 2, dtype: object

Prediction :  Yes

In [ ]:
# predict with custom input
chef.predict(c45_model, param = ['Overcast', 'Hot', 'High', 'Weak'])

'Yes'

**IMPLEMENTASI 2**

menentukan status kepemilikan rumah berdasarkan fitur yag ada

In [ ]:
dfBank = pd.read_csv('/content/drive/MyDrive/kuliah/Smester 5/big data & data mining/p10/bank-full.csv')
dfBank.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,Target
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [ ]:
dfBank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  object
 16  Target     45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB

In [ ]:
categorical=[]
for col, value in dfBank.iteritems():
  if value.dtype == 'object':
    categorical.append(col)

# store numerical columns in list
dfBank = dfBank[categorical]

In [ ]:
dfBank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   job        45211 non-null  object
 1   marital    45211 non-null  object
 2   education  45211 non-null  object
 3   default    45211 non-null  object
 4   housing    45211 non-null  object
 5   loan       45211 non-null  object
 6   contact    45211 non-null  object
 7   month      45211 non-null  object
 8   poutcome   45211 non-null  object
 9   Target     45211 non-null  object
dtypes: object(10)
memory usage: 3.4+ MB

In [ ]:
from sklearn import preprocessing

le = preprocessing.LabelEncoder()

df_feature_select = dfBank.copy()

for columnName in df_feature_select:
  df_feature_select[columnName] = le.fit_transform(df_feature_select[columnName])

df_feature_select.head()

,job,marital,education,default,housing,loan,contact,month,poutcome,Target
0,4,1,2,0,1,0,2,8,3,0
1,9,2,1,0,1,0,2,8,3,0
2,2,1,1,0,1,1,2,8,3,0
3,1,1,3,0,1,0,2,8,3,0
4,11,2,3,0,0,0,2,8,3,0

In [ ]:
cor = df_feature_select.corr()

# cerrelation with output variable
corr_target = abs(cor['housing'])

# selecting highly correlated features
relevant_features = corr_target[cor_target > 0.1]
relevant_features

job        0.125363
housing    1.000000
contact    0.188123
month      0.271481
Target     0.139173
Name: housing, dtype: float64

In [ ]:
relevant_feature_col = ['job','contact','month','Target','housing']

In [ ]:
selected_df = dfBank[relevant_feature_col]

In [ ]:
selected_df.head()

            job  contact month Target housing
0    management  unknown   may     no     yes
1    technician  unknown   may     no     yes
2  entrepreneur  unknown   may     no     yes
3   blue-collar  unknown   may     no     yes
4       unknown  unknown   may     no      no

**SPLIT DATA**

In [ ]:
df_train = selected_df.loc[selected_df['housing'] == 'yes'].head(200)
df_train_no = selected_df.loc[selected_df['housing'] == 'no'].head(200)
df_train = df_train.append(df_train_no).reset_index().drop('index', 1)

<ipython-input-47-49465634f760>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df_train = df_train.append(df_train_no).reset_index().drop('index', 1)

In [ ]:
df_test = selected_df.loc[selected_df['housing'] == 'yes'].tail(40)
df_test_no = selected_df.loc[selected_df['housing'] == 'no'].tail(40)
df_test = df_test.append(df_train_no).reset_index().drop('index', 1)

<ipython-input-57-0a9f37a9ede6>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df_test = df_test.append(df_train_no).reset_index().drop('index', 1)

In [ ]:
config = {'algorithm' : 'C4.5'}

c45_model2 = chef.fit(df_train, config, target_label = 'housing')

[INFO]:  1 CPU cores will be allocated in parallel running
C4.5  tree is going to be built...
-------------------------
finished in  4.23604679107666  seconds
-------------------------
Evaluate  train set
-------------------------
Accuracy:  54.0 % on  400  instances
Labels:  ['yes' 'no']
Confusion matrix:  [[160, 144], [40, 56]]
Precision:  52.6316 %, Recall:  80.0 %, F1:  63.4921 %

In [ ]:
with open('/content/outputs/rules/rules.py', encoding='utf-8') as f:
  for line in f:
    print(line.strip())

def findDecision(obj): #obj[0]: job, obj[1]: contact, obj[2]: month, obj[3]: Target
# {"feature": "job", "instances": 400, "metric_value": 1.0, "depth": 1}
if obj[0] == 'blue-collar':
# {"feature": "Target", "instances": 94, "metric_value": 0.9987, "depth": 2}
if obj[3] == 'no':
# {"feature": "contact", "instances": 93, "metric_value": 0.9979, "depth": 3}
if obj[1] == 'unknown':
# {"feature": "month", "instances": 93, "metric_value": 0.9979, "depth": 4}
if obj[2] == 'may':
return 'yes'
else: return 'yes'
else: return 'yes'
elif obj[3] == 'yes':
return 'no'
else: return 'no'
elif obj[0] == 'management':
# {"feature": "contact", "instances": 66, "metric_value": 0.9993, "depth": 2}
if obj[1] == 'unknown':
# {"feature": "month", "instances": 66, "metric_value": 0.9993, "depth": 3}
if obj[2] == 'may':
# {"feature": "Target", "instances": 66, "metric_value": 0.9993, "depth": 4}
if obj[3] == 'no':
return 'yes'
else: return 'yes'
else: return 'yes'
else: return 'yes'
elif obj[0] == 'technician':
# {"feature": "Target", "instances": 63, "metric_value": 0.9984, "depth": 2}
if obj[3] == 'no':
# {"feature": "contact", "instances": 62, "metric_value": 0.997, "depth": 3}
if obj[1] == 'unknown':
# {"feature": "month", "instances": 62, "metric_value": 0.997, "depth": 4}
if obj[2] == 'may':
return 'no'
else: return 'no'
else: return 'no'
elif obj[3] == 'yes':
return 'yes'
else: return 'yes'
elif obj[0] == 'services':
# {"feature": "Target", "instances": 53, "metric_value": 0.9874, "depth": 2}
if obj[3] == 'no':
# {"feature": "contact", "instances": 52, "metric_value": 0.9904, "depth": 3}
if obj[1] == 'unknown':
# {"feature": "month", "instances": 52, "metric_value": 0.9904, "depth": 4}
if obj[2] == 'may':
return 'yes'
else: return 'yes'
else: return 'yes'
elif obj[3] == 'yes':
return 'yes'
else: return 'yes'
elif obj[0] == 'admin.':
# {"feature": "Target", "instances": 50, "metric_value": 0.9988, "depth": 2}
if obj[3] == 'no':
# {"feature": "contact", "instances": 46, "metric_value": 1.0, "depth": 3}
if obj[1] == 'unknown':
# {"feature": "month", "instances": 46, "metric_value": 1.0, "depth": 4}
if obj[2] == 'may':
return 'yes'
else: return 'yes'
else: return 'yes'
elif obj[3] == 'yes':
# {"feature": "contact", "instances": 4, "metric_value": 0.8113, "depth": 3}
if obj[1] == 'unknown':
# {"feature": "month", "instances": 4, "metric_value": 0.8113, "depth": 4}
if obj[2] == 'may':
return 'no'
else: return 'no'
else: return 'no'
else: return 'no'
elif obj[0] == 'retired':
# {"feature": "contact", "instances": 29, "metric_value": 0.9991, "depth": 2}
if obj[1] == 'unknown':
# {"feature": "month", "instances": 29, "metric_value": 0.9991, "depth": 3}
if obj[2] == 'may':
# {"feature": "Target", "instances": 29, "metric_value": 0.9991, "depth": 4}
if obj[3] == 'no':
return 'yes'
else: return 'yes'
else: return 'yes'
else: return 'yes'
elif obj[0] == 'entrepreneur':
# {"feature": "contact", "instances": 12, "metric_value": 1.0, "depth": 2}
if obj[1] == 'unknown':
# {"feature": "month", "instances": 12, "metric_value": 1.0, "depth": 3}
if obj[2] == 'may':
# {"feature": "Target", "instances": 12, "metric_value": 1.0, "depth": 4}
if obj[3] == 'no':
return 'yes'
else: return 'yes'
else: return 'yes'
else: return 'yes'
elif obj[0] == 'self-employed':
# {"feature": "contact", "instances": 11, "metric_value": 0.994, "depth": 2}
if obj[1] == 'unknown':
# {"feature": "month", "instances": 11, "metric_value": 0.994, "depth": 3}
if obj[2] == 'may':
# {"feature": "Target", "instances": 11, "metric_value": 0.994, "depth": 4}
if obj[3] == 'no':
return 'no'
else: return 'no'
else: return 'no'
else: return 'no'
elif obj[0] == 'unemployed':
# {"feature": "contact", "instances": 11, "metric_value": 0.9457, "depth": 2}
if obj[1] == 'unknown':
# {"feature": "month", "instances": 11, "metric_value": 0.9457, "depth": 3}
if obj[2] == 'may':
# {"feature": "Target", "instances": 11, "metric_value": 0.9457, "depth": 4}
if obj[3] == 'no':
return 'no'
else: return 'no'
else: return 'no'
else: return 'no'
elif obj[0] == 'housemaid':
# {"feature": "contact", "instances": 4, "metric_value": 0.8113, "depth": 2}
if obj[1] == 'unknown':
# {"feature": "month", "instances": 4, "metric_value": 0.8113, "depth": 3}
if obj[2] == 'may':
# {"feature": "Target", "instances": 4, "metric_value": 0.8113, "depth": 4}
if obj[3] == 'no':
return 'no'
else: return 'no'
else: return 'no'
else: return 'no'
elif obj[0] == 'student':
# {"feature": "contact", "instances": 4, "metric_value": 1.0, "depth": 2}
if obj[1] == 'unknown':
# {"feature": "month", "instances": 4, "metric_value": 1.0, "depth": 3}
if obj[2] == 'may':
# {"feature": "Target", "instances": 4, "metric_value": 1.0, "depth": 4}
if obj[3] == 'no':
return 'yes'
else: return 'yes'
else: return 'yes'
else: return 'yes'
elif obj[0] == 'unknown':
return 'no'
else: return 'no'

**PREDICTION**

In [ ]:
chef.predict(c45_model, param = ['Overcast', 'Hot', 'High', 'Weak'])

'no'

In [ ]:
print('Row : \n : ', dfBank.loc[2])
print('\nPrediction : ', chef.predict(c45_model2, dfBank.loc[2]))

Row :
 :  job          entrepreneur
marital           married
education       secondary
default                no
housing               yes
loan                  yes
contact           unknown
month                 may
poutcome          unknown
Target                 no
Name: 2, dtype: object

Prediction :  yes

In [ ]:
predicted = []
for row in df_test.index:
  predicted.append(chef.predict(c45_model2, df_test.loc[row]))

In [ ]:
from sklearn.metrics import *
print(classification_report(df_test['housing'].values, predicted, zero_division=0))

              precision    recall  f1-score   support

          no       0.81      0.28      0.42       200
         yes       0.16      0.68      0.26        40

    accuracy                           0.35       240
   macro avg       0.48      0.48      0.34       240
weighted avg       0.70      0.35      0.39       240