In [3]:
list1 = ['Bigdata & Data Mining', 'BigData & Predictive Analytic', 2022, 2022]
list2 = ['buku', 'pensil', 'penggaris', 'spidol', 'bolpoin', 'penghapus']
list3 = ['a', 'b', 'c', 'd']

In [5]:
print("list1[0]: ", list1[0])
print("list2[1:5]: ", list2[1:5])

list1[0]:  Bigdata & Data Mining
list2[1:5]:  ['pensil', 'penggaris', 'spidol', 'bolpoin']

In [10]:
print("list2[2:4]:", list3[2:4])

list2[2:4]: ['c', 'd']

In [9]:
print(list2[1], ' ', list2[2])
print(list2[1:3])

pensil   penggaris
['pensil', 'penggaris']

dataframe

In [12]:
import pandas as pd

data = {
    'buah': ['apel', 'pisang', 'jeruk', 'nanas', 'durian'],
    'sayur': ['bayam', 'sawi', 'wortel', 'kentang', 'kacang'],
    'hewan': ['kucing', 'kambing', 'sapi', 'kelinci', 'buaya']
}

df = pd.DataFrame(data)
df.head()

     buah    sayur    hewan
0    apel    bayam   kucing
1  pisang     sawi  kambing
2   jeruk   wortel     sapi
3   nanas  kentang  kelinci
4  durian   kacang    buaya

In [13]:
print(data['hewan'][2])

sapi

In [14]:
print(data['sayur'][3], " ", data['hewan'][4])

kentang   buaya

tuple

In [15]:
tup1 = ('Bigdata & Data Mining', 'BigData & Predictive Analytic', 2022, 2022)
tup2 = (1, 2, 3, 4, 5)
tup3 = ('a', 'b', 'c', 'd')

In [16]:
type (tup1)

tuple

In [17]:
type (list1)

list

In [18]:
len(tup2)

5

In [20]:
print("tup1[0]:", tup1[0])
print("tup2[1:5]:", tup1[1:5])

tup1[0]: Bigdata & Data Mining
tup2[1:5]: ('BigData & Predictive Analytic', 2022, 2022)

In [21]:
print(tup2, ' & ', tup3)
print(tup2+tup3)

(1, 2, 3, 4, 5)  &  ('a', 'b', 'c', 'd')
(1, 2, 3, 4, 5, 'a', 'b', 'c', 'd')

In [24]:
print(*tup2)

1 2 3 4 5

In [26]:
print(type(tup1))
print(type(tup2))
print(type(tup3))

<class 'tuple'>
<class 'tuple'>
<class 'tuple'>

In [29]:
tup_nim = (3,7,1,4)
print(tup_nim)

(3, 7, 1, 4)

dictionary berisi key dan value

In [31]:
dict = {'Name': 'Zara', 'Age': 20, 'Class': 'BigData1'}

print("dict['Name']: ", dict['Name'])
print("dict['Age]: ", dict['Age'])

print(dict)

dict['Name']:  Zara
dict['Age]:  20
{'Name': 'Zara', 'Age': 20, 'Class': 'BigData1'}

In [34]:
# update dictionary
dict['Age']= 10
print(dict)

{'Name': 'Zara', 'Age': 10, 'Class': 'BigData1'}

In [36]:
dict = [dict, {'Nama':'Zr','Age':11,'Class':'BigData0'}]
dict = [{'Nama':'Zara','Age':20,'Class':'BigData1'},{'Nama':'Zr','Age':11,'Class':'BigData0'}]
print(dict)

[{'Nama': 'Zara', 'Age': 20, 'Class': 'BigData1'}, {'Nama': 'Zr', 'Age': 11, 'Class': 'BigData0'}]

In [38]:
data = [{'Nama':'Zara','Age':20,'Class':'BigData1'},
        {'Nama':'Zr','Age':15,'Class':'BigData2'},
        {'Nama':'AR','Age':16,'Class':'BigData3'}]
df = pd.DataFrame(data)
df.head()

   Nama  Age     Class
0  Zara   20  BigData1
1    Zr   15  BigData2
2    AR   16  BigData3

In [39]:
df = pd.read_csv('/content/sample_data/california_housing_test.csv')
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [40]:
df.head(15)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
5,-119.56,36.51,37.0,1018.0,213.0,663.0,204.0,1.6635,67000.0
6,-121.43,38.63,43.0,1009.0,225.0,604.0,218.0,1.6641,67000.0
7,-120.65,35.48,19.0,2310.0,471.0,1341.0,441.0,3.2250,166900.0
8,-122.84,38.40,15.0,3080.0,617.0,1446.0,599.0,3.6696,194400.0
9,-118.02,34.08,31.0,2402.0,632.0,2830.0,603.0,2.3333,164200.0
10,-118.24,33.98,45.0,972.0,249.0,1288.0,261.0,2.2054,125000.0
11,-119.12,35.85,37.0,736.0,166.0,564.0,138.0,2.4167,58300.0
12,-121.93,37.25,36.0,1089.0,182.0,535.0,170.0,4.6900,252600.0
13,-117.03,32.97,16.0,3936.0,694.0,1935.0,659.0,4.5625,231200.0
14,-117.97,33.73,27.0,2097.0,325.0,1217.0,331.0,5.7121,222500.0

In [46]:
df.loc[1:5]
df.loc[1:5, ['longitude','longitude', 'housing_median_age']]

   longitude  longitude  housing_median_age
1    -118.30    -118.30                43.0
2    -117.81    -117.81                27.0
3    -118.36    -118.36                28.0
4    -119.67    -119.67                19.0
5    -119.56    -119.56                37.0